CREATE TABLE MEMBER (
	M_NO	NUMBER		NOT NULL,
	M_ID	VARCHAR2(500)		NOT NULL,
	M_PW	VARCHAR2(500)		NULL,
	M_NAME	VARCHAR2(500)		NULL,
	M_EMAIL	VARCHAR2(500)		NULL,
	M_PHONE	NUMBER		NULL,
	M_ADDRESS	VARCHAR2(1000)		NULL,
	M_GENDER	CHAR(1)		NULL,
	M_BIRTH	DATE		NULL,
	M_JOINDATE	DATE		NULL,
	M_AUTHORIZATION	CHAR(1)		NULL,
	M_STATUS	CHAR(1)		NULL,
	M_JOINWAY	VARCHAR2(20)		NULL
);

CREATE TABLE NOTICE (
	N_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	N_TITLE	VARCHAR2(50)		NULL,
	N_CONTENT	VARCHAR2(2000)		NULL,
	N_ORIGINAL_FILENAME	VARCHAR2(100)		NULL,
	N_RENAMED_FILENAME	VARCHAR2(100)		NULL,
	N_READCOUNT	NUMBER		NULL,
	N_STATUS	VARCHAR2(1)		NULL,
	N_CREATE_DATE	DATE		NULL,
	N_TOPTITLE	VARCHAR2(50)		NULL
);

CREATE TABLE CONTENTS (
	C_NO	NUMBER		NOT NULL,
	C_TITLE	VARCHAR2(300)		NULL,
	C_TYPE	VARCHAR2(20)		NULL,
	C_GENRE	VARCHAR2(20)		NULL,
	C_YEAR	NUMBER		NULL,
	C_NATION	VARCHAR2(20)		NULL,
	C_INFO	VARCHAR2(3000)		NULL,
	C_SYNOP	VARCHAR2(3000)		NULL,
	C_BRGB	VARCHAR2(3000)		NULL,
	C_OBIMG	VARCHAR2(3000)		NULL,
	C_BIMG	VARCHAR2(3000)		NULL,
	C_OPIMG	VARCHAR2(3000)		NULL,
	C_PIMG	VARCHAR2(3000)		NULL,
	C_VIDEO	VARCHAR2(3000)		NULL,
	C_DATE	DATE		NULL,
	C_STATUS	VARCHAR2(1)		NULL
);

CREATE TABLE COMMENTS (
	CM_NO	NUMBER		NOT NULL,
	B_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	CM_CONTENT	VARCHAR2(1000)		NULL,
	CM_DATE	DATE		NULL
);

CREATE TABLE LIKES (
	M_NO	NUMBER		NOT NULL,
	C_NO	NUMBER		NOT NULL
);

CREATE TABLE REVIEW (
	R_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	R_DATE	DATE		NULL,
	R_CONTENT	VARCHAR2(100)		NULL
);

CREATE TABLE PEOPLE (
	PEOPLE_NO	NUMBER		NOT NULL,
	PEOPLE_ORIGINAL_FILENAME	VARCHAR2(3000)		NULL,
	PEOPLE_RENAMED_FILENAME	VARCHAR2(3000)		NULL,
	PEOPLE_NAME	VARCHAR2(300)		NOT NULL,
	PEOPLE_JOB	VARCHAR2(300)		NULL,
	PEOPLE_DEBUT	DATE		NULL,
	PEOPLE_BIRTH	DATE		NULL,
	PEOPLE_AWARD	VARCHAR2(500)		NULL,
	PEOPLE_GENDER	VARCHAR2(50)		NULL
);

CREATE TABLE CART (
	M_NO	NUMBER		NOT NULL,
	P_NO	NUMBER		NOT NULL
);

CREATE TABLE PAY (
	PAY_NO	NUMBER		NOT NULL,
	PAY_MERCHANT	VARCHAR2(30)		NULL,
	PAY_ACOUNT	NUMBER		NULL,
	PAY_METHOD	VARCHAR2(20)		NULL
);

CREATE TABLE VISIT (
	V_NO	NUMBER		NOT NULL,
	V_DATE	DATE		NOT NULL,
	V_COUNT	NUMBER		NULL
);

CREATE TABLE CONTENTSPEOPLE (
	C_NO	NUMBER		NOT NULL,
	PEOPLE_NO	NUMBER		NOT NULL,
	C_ROLE	VARCHAR(10)		NULL
);

CREATE TABLE PRODUCT (
	P_NO	NUMBER		NOT NULL,
	P_NAME	VARCHAR2(300)		NULL,
	P_PRICE	NUMBER		NULL,
	P_QTT	NUMBER		NULL,
	P_CONTENTS	VARCHAR2(3000)		NULL,
	P_VIEW	NUMBER		NULL,
	P_DATE	DATE		NULL,
	P_STATUS	VARCHAR2(1)		NULL,
	P_ORIGINFILE	VARCHAR2(50)		NULL,
	P_RENAMEFILE	VARCHAR2(50)		NULL
);

CREATE TABLE ORDERS (
	O_NO	NUMBER		NOT NULL,
	P_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	O_DATE	DATE		NULL,
	O_QTT	NUMBER		NULL,
	O_ADRESS	VARCHAR2(60)		NULL,
	O_PRICE	NUMBER		NULL
);

CREATE TABLE CVIEW (
	CV_NO	NUMBER		NOT NULL,
	CV_DATE	DATE		NOT NULL,
	CV_COUNT	NUMBER		NULL
);

CREATE TABLE BOARD (
	B_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	B_TYPE	VARCHAR2(10)		NULL,
	B_TITLE	VARCHAR2(1000)		NULL,
	B_TIMESTAMP	TIMESTAMP		NULL,
	B_CONTENT	VARCHAR2(4000)		NULL,
	B_ORIGINAL_FILENAME	VARCHAR2(100)		NULL,
	B_RENAMED_FILENAME	VARCHAR2(100)		NULL,
	B_VIEW	NUMBER		NULL,
	B_STATUS	VARCHAR2(1)		NULL,
	B_ANSWER_STATUS	VARCHAR2(1)		NULL
);

CREATE TABLE RATE (
	RATE_NO	NUMBER		NULL,
	C_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	RATE_STAR	NUMBER		NULL,
	RATE_COMMENT	VARCHAR2(3000)		NULL,
	RATE_DATE	DATE		NULL,
	RATE_LIKE	NUMBER		NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	M_NO
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	N_NO
);

ALTER TABLE CONTENTS ADD CONSTRAINT PK_CONTENTS PRIMARY KEY (
	C_NO
);

ALTER TABLE COMMENTS ADD CONSTRAINT PK_COMMENTS PRIMARY KEY (
	CM_NO
);

ALTER TABLE REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY (
	R_NO
);

ALTER TABLE PEOPLE ADD CONSTRAINT PK_PEOPLE PRIMARY KEY (
	PEOPLE_NO
);

ALTER TABLE CART ADD CONSTRAINT PK_CART PRIMARY KEY (
	M_NO,
	P_NO
);

ALTER TABLE PAY ADD CONSTRAINT PK_PAY PRIMARY KEY (
	PAY_NO
);

ALTER TABLE VISIT ADD CONSTRAINT PK_VISIT PRIMARY KEY (
	V_NO
);

ALTER TABLE CONTENTSPEOPLE ADD CONSTRAINT PK_CONTENTSPEOPLE PRIMARY KEY (
	C_NO,
	PEOPLE_NO
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
	P_NO
);

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (
	O_NO,
	P_NO,
	M_NO
);

ALTER TABLE CVIEW ADD CONSTRAINT PK_CVIEW PRIMARY KEY (
	CV_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	B_NO
);

ALTER TABLE RATE ADD CONSTRAINT PK_RATE PRIMARY KEY (
	RATE_NO
);

ALTER TABLE CART ADD CONSTRAINT FK_MEMBER_TO_CART_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE CART ADD CONSTRAINT FK_PRODUCT_TO_CART_1 FOREIGN KEY (
	P_NO
)
REFERENCES PRODUCT (
	P_NO
);


ALTER TABLE CONTENTSPEOPLE ADD CONSTRAINT FK_CONTENTS_TO_CONTENTSPEOPLE_1 FOREIGN KEY (
	C_NO
)
REFERENCES CONTENTS (
	C_NO
);

ALTER TABLE CONTENTSPEOPLE ADD CONSTRAINT FK_PEOPLE_TO_CONTENTSPEOPLE_1 FOREIGN KEY (
	PEOPLE_NO
)
REFERENCES PEOPLE (
	PEOPLE_NO
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_PRODUCT_TO_ORDERS_1 FOREIGN KEY (
	P_NO
)
REFERENCES PRODUCT (
	P_NO
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_MEMBER_TO_ORDERS_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

-- 테스트 값 
CREATE SEQUENCE CONTENTS_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
       
CREATE SEQUENCE RATE_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'공조2: 인터내셔날', 
'영화',
'액션',
2022,
'한국', 
'개요',
'공조 이즈 백! 이번엔 삼각 공조다! 남한으로 숨어든 글로벌 범죄 조직을 잡기 위해 새로운 공조 수사에 투입된 북한 형사 ‘림철령’(현빈).',
'rgb(155,155,155)',
'공조 포스터 원본명',
'공조 포스터 변경명',
'공조 프로필 포스터 원본명',
'공조 프로필 포스터 변경명',
'http:dfjkdsjfl.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'모가디슈', 
'영화',
'액션',
2022,
'한국', 
'개요',
'내전으로 고립된 낯선 도시, 모가디슈 지금부터 우리의 목표는 오로지 생존이다! 대한민국이 UN가입을 위해 동분서주하던 시기 1991년 소말리아의 수도 모가디슈에서는 일촉즉발의 내전이 일어난다.',
'rgb(120,120,120)',
'모가디슈 포스터 원본명',
'모가디슈 포스터 변경명',
'모가디슈 프로필 포스터 원본명',
'모가디슈 프로필 포스터 변경명',
'http:htorejwlj.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'놉', 
'영화',
'미스터리',
2022,
'미국', 
'개요',
'거대하고, 주목받길 원하고, 미쳤다. 나쁜 기적이라는 것도 있을까? ',
'rgb(100,100,100)',
'놉 포스터 원본명',
'놉 포스터 변경명',
'놉 프로필 포스터 원본명',
'놉 프로필 포스터 변경명',
'http:dkfjsldj.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'외모지상주의', 
'웹툰',
'드라마',
2022,
'한국', 
'개요',
'못생기고 뚱뚱하다고 괴롭힘을 당하며 루저 인생만 살아온 내가 잘생겨졌다는 이유로 인싸가 됐다.',
'rgb(50,50,50)',
'외모지상주의 포스터 원본명',
'외모지상주의 포스터 변경명',
'외모지상주의 프로필 포스터 원본명',
'외모지상주의 프로필 포스터 변경명',
'http:djfdskjflsd.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'외모지상주의', 
'웹툰',
'드라마',
2022,
'한국', 
'개요',
'못생기고 뚱뚱하다고 괴롭힘을 당하며 루저 인생만 살아온 내가 잘생겨졌다는 이유로 인싸가 됐다.',
'rgb(50,50,50)',
'외모지상주의 포스터 원본명',
'외모지상주의 포스터 변경명',
'외모지상주의 프로필 포스터 원본명',
'외모지상주의 프로필 포스터 변경명',
'http:djfdskjflsd.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'99강화나무몽둥이', 
'웹툰',
'판타지',
2022,
'한국', 
'개요',
'약육강식이 진리인 가상 현실 게임 '크로노 라이프'. 허접이라며 무시만 당하던 '나'는 우연히 얻은 초보용 기본 무기 '나무 뭉둥이' 를 +99 강화까지 성공하게 되고,',
'rgb(70,70,70)',
'강화나무몽둥이 포스터 원본명',
'강화나무몽둥이 포스터 변경명',
'강화나무몽둥이 프로필 포스터 원본명',
'강화나무몽둥이 프로필 포스터 변경명',
'http:wqjklldf.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'으라차차내인생', 
'드라마',
'드라마',
2022,
'한국', 
'개요',
'조카의 엄마가 되기로 선택한 싱글맘, 서동희가 세상을 향해 펼치는 고군분투기를 담은 드라마',
'rgb(50,50,50)',
'으라차차내인생 포스터 원본명',
'으라차차내인생 포스터 변경명',
'으라차차내인생 프로필 포스터 원본명',
'으라차차내인생 프로필 포스터 변경명',
'http:wqjklldf.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'황금가면', 
'드라마',
'드라마',
2022,
'한국', 
'개요',
'그릇된 욕망과 탐욕이 빚어낸 비극으로, 세 여자의 광기 어린 싸움 속에서 삶의 해답을 찾아가는 이야기',
'rgb(50,50,50)',
'황금가면 포스터 원본명',
'황금가면 포스터 변경명',
'황금가면 프로필 포스터 원본명',
'황금가면 프로필 포스터 변경명',
'http:dkfjsldj.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'아버지의해방일지', 
'도서',
'소설',
2022,
'한국', 
'개요',
'소설은 ‘전직 빨치산’ 아버지의 죽음 이후 3일간의 시간만을 현재적 배경으로 다루지만, 장례식장에서 얽히고설킨 이야기를 따라가다보면 해방 이후 70년 현대사의 질곡이 생생하게 드러난다.',
'rgb(50,50,50)',
'아버지의해방일지 포스터 원본명',
'아버지의해방일지 포스터 변경명',
'아버지의해방일지 프로필 포스터 원본명',
'아버지의해방일지 프로필 포스터 변경명',
'http:dsjfjdsfj.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'역행자', 
'도서',
'자기계발서',
2022,
'한국', 
'개요',
'대부분의 사람들은 유전자와 본성의 명령을 그대로 따르기 때문에 평범함을 벗어날 수 없다. 하지만 정작 자신은 이를 모른 채 ‘나는 달라’ 하는 자의식에 사로잡혀서 무한 합리화에 빠져 살아간다. ',
'rgb(50,50,50)',
'역행자 포스터 원본명',
'역행자 포스터 변경명',
'역행자 프로필 포스터 원본명',
'역행자 프로필 포스터 변경명',
'http:dsjfjdsfj.com',
SYSDATE,
'Y'
);

INSERT INTO CONTENTS
VALUES 
(CONTENTS_SEQ.NEXTVAL, 
'하얼빈', 
'도서',
'역사소설',
2022,
'한국', 
'개요',
'"나는 안중근의 대의보다도 실탄 일곱 발과 여비 백 루블을 지니고 블라디보스토크에서 하얼빈으로 향하는 그의 가난과 청춘과 그의 살아 있는 몸에 관하여 말하려 했다." ',
'rgb(50,50,50)',
'하얼빈 포스터 원본명',
'하얼빈 포스터 변경명',
'하얼빈 프로필 포스터 원본명',
'하얼빈 프로필 포스터 변경명',
'http:dsjfjdsfj.com',
SYSDATE,
'Y'
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
01,
01,
3.5,
'너무 재미있다.',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
01,
02,
3.5,
'매우 재미있다.',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
01,
03,
3.5,
'아주 재미있다.',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
02,
04,
3.5,
'그냥 그렇다',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
02,
05,
3.5,
'그냥 그렇다',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
02,
06,
3.5,
'그냥 그렇다',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
03,
07,
3.5,
'재밌다',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
03,
08,
3.5,
'재밌다',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
03,
09,
3.5,
'재밌다',
SYSDATE,
7
);

INSERT INTO RATE
VALUES 
(RATE_SEQ.NEXTVAL, 
04,
10,
3.5,
'유익',
SYSDATE,
7
);