CREATE TABLE MEMBER (
	M_NO	NUMBER		NOT NULL,
	M_ID	VARCHAR2(500)		NOT NULL,
	M_PW	VARCHAR2(500)		NULL,
	M_NAME	VARCHAR2(500)		NULL,
	M_EMAIL	VARCHAR2(500)		NULL,
	M_PHONE	NUMBER		NULL,
	M_ADDRESS	VARCHAR2(1000)		NULL,
	M_GENDER	CHAR(1)		NULL,
	M_BIRTH	DATE		NULL,
	M_JOINDATE	DATE		NULL,
	M_AUTHORIZATION	CHAR(1)		NULL,
	M_STATUS	CHAR(1)		NULL,
	M_JOINWAY	VARCHAR2(20)		NULL
);

CREATE TABLE NOTICE (
	N_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	N_TITLE	VARCHAR2(50)		NULL,
	N_CONTENT	VARCHAR2(2000)		NULL,
	N_ORIGINAL_FILENAME	VARCHAR2(100)		NULL,
	N_RENAMED_FILENAME	VARCHAR2(100)		NULL,
	N_READCOUNT	NUMBER		NULL,
	N_STATUS	VARCHAR2(1)		NULL,
	N_CREATE_DATE	DATE		NULL,
	N_TOPTITLE	VARCHAR2(50)		NULL
);

CREATE TABLE CONTENTS (
	C_NO	NUMBER		NOT NULL,
	C_TITLE	VARCHAR2(300)		NULL,
	C_TYPE	VARCHAR2(20)		NULL,
	C_GENRE	VARCHAR2(20)		NULL,
	C_YEAR	NUMBER		NULL,
	C_NATION	VARCHAR2(20)		NULL,
	C_INFO	VARCHAR2(3000)		NULL,
	C_SYNOP	VARCHAR2(3000)		NULL,
	C_BRGB	VARCHAR2(3000)		NULL,
	C_OBIMG	VARCHAR2(3000)		NULL,
	C_BIMG	VARCHAR2(3000)		NULL,
	C_OPIMG	VARCHAR2(3000)		NULL,
	C_PIMG	VARCHAR2(3000)		NULL,
	C_VIDEO	VARCHAR2(3000)		NULL,
	C_DATE	DATE		NULL,
	C_STATUS	VARCHAR2(1)		NULL
);

CREATE TABLE COMMENTS (
	CM_NO	NUMBER		NOT NULL,
	B_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	CM_CONTENT	VARCHAR2(1000)		NULL,
	CM_DATE	DATE		NULL
);

CREATE TABLE LIKES (
	M_NO	NUMBER		NOT NULL,
	C_NO	NUMBER		NOT NULL
);

CREATE TABLE REVIEW (
	R_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	R_DATE	DATE		NULL,
	R_CONTENT	VARCHAR2(100)		NULL
);

CREATE TABLE PEOPLE (
	PEOPLE_NO	NUMBER		NOT NULL,
	PEOPLE_ORIGINAL_FILENAME	VARCHAR2(3000)		NULL,
	PEOPLE_RENAMED_FILENAME	VARCHAR2(3000)		NULL,
	PEOPLE_NAME	VARCHAR2(300)		NOT NULL,
	PEOPLE_JOB	VARCHAR2(300)		NULL,
	PEOPLE_DEBUT	DATE		NULL,
	PEOPLE_BIRTH	DATE		NULL,
	PEOPLE_AWARD	VARCHAR2(500)		NULL,
	PEOPLE_GENDER	VARCHAR2(50)		NULL
);

CREATE TABLE CART (
	M_NO	NUMBER		NOT NULL,
	P_NO	NUMBER		NOT NULL
);

CREATE TABLE PAY (
	PAY_NO	NUMBER		NOT NULL,
	PAY_MERCHANT	VARCHAR2(30)		NULL,
	PAY_ACOUNT	NUMBER		NULL,
	PAY_METHOD	VARCHAR2(20)		NULL
);

CREATE TABLE VISIT (
	V_NO	NUMBER		NOT NULL,
	V_DATE	DATE		NOT NULL,
	V_COUNT	NUMBER		NULL
);

CREATE TABLE CONTENTSPEOPLE (
	C_NO	NUMBER		NOT NULL,
	PEOPLE_NO	NUMBER		NOT NULL,
	C_ROLE	VARCHAR(10)		NULL
);

CREATE TABLE PRODUCT (
	P_NO	NUMBER		NOT NULL,
	P_NAME	VARCHAR2(300)		NULL,
	P_PRICE	NUMBER		NULL,
	P_QTT	NUMBER		NULL,
	P_CONTENTS	VARCHAR2(3000)		NULL,
	P_VIEW	NUMBER		NULL,
	P_DATE	DATE		NULL,
	P_STATUS	VARCHAR2(1)		NULL,
	P_ORIGINFILE	VARCHAR2(50)		NULL,
	P_RENAMEFILE	VARCHAR2(50)		NULL
);

CREATE TABLE ORDERS (
	O_NO	NUMBER		NOT NULL,
	P_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	O_DATE	DATE		NULL,
	O_QTT	NUMBER		NULL,
	O_ADRESS	VARCHAR2(60)		NULL,
	O_PRICE	NUMBER		NULL
);

CREATE TABLE CVIEW (
	CV_NO	NUMBER		NOT NULL,
	CV_DATE	DATE		NOT NULL,
	CV_COUNT	NUMBER		NULL
);

CREATE TABLE BOARD (
	B_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	B_TYPE	VARCHAR2(10)		NULL,
	B_TITLE	VARCHAR2(1000)		NULL,
	B_TIMESTAMP	TIMESTAMP		NULL,
	B_CONTENT	VARCHAR2(4000)		NULL,
	B_ORIGINAL_FILENAME	VARCHAR2(100)		NULL,
	B_RENAMED_FILENAME	VARCHAR2(100)		NULL,
	B_VIEW	NUMBER		NULL,
	B_STATUS	VARCHAR2(1)		NULL,
	B_ANSWER_STATUS	VARCHAR2(1)		NULL
);

CREATE TABLE RATE (
	RATE_NO	NUMBER		NULL,
	C_NO	NUMBER		NOT NULL,
	M_NO	NUMBER		NOT NULL,
	RATE_STAR	NUMBER		NULL,
	RATE_COMMENT	VARCHAR2(3000)		NULL,
	RATE_DATE	DATE		NULL,
	RATE_LIKE	NUMBER		NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	M_NO
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	N_NO
);

ALTER TABLE CONTENTS ADD CONSTRAINT PK_CONTENTS PRIMARY KEY (
	C_NO
);

ALTER TABLE COMMENTS ADD CONSTRAINT PK_COMMENTS PRIMARY KEY (
	CM_NO
);

ALTER TABLE REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY (
	R_NO
);

ALTER TABLE PEOPLE ADD CONSTRAINT PK_PEOPLE PRIMARY KEY (
	PEOPLE_NO
);

ALTER TABLE CART ADD CONSTRAINT PK_CART PRIMARY KEY (
	M_NO,
	P_NO
);

ALTER TABLE PAY ADD CONSTRAINT PK_PAY PRIMARY KEY (
	PAY_NO
);

ALTER TABLE VISIT ADD CONSTRAINT PK_VISIT PRIMARY KEY (
	V_NO
);

ALTER TABLE CONTENTSPEOPLE ADD CONSTRAINT PK_CONTENTSPEOPLE PRIMARY KEY (
	C_NO,
	PEOPLE_NO
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
	P_NO
);

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (
	O_NO,
	P_NO,
	M_NO
);

ALTER TABLE CVIEW ADD CONSTRAINT PK_CVIEW PRIMARY KEY (
	CV_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	B_NO
);

ALTER TABLE RATE ADD CONSTRAINT PK_RATE PRIMARY KEY (
	RATE_NO
);

ALTER TABLE CART ADD CONSTRAINT FK_MEMBER_TO_CART_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE CART ADD CONSTRAINT FK_PRODUCT_TO_CART_1 FOREIGN KEY (
	P_NO
)
REFERENCES PRODUCT (
	P_NO
);


ALTER TABLE CONTENTSPEOPLE ADD CONSTRAINT FK_CONTENTS_TO_CONTENTSPEOPLE_1 FOREIGN KEY (
	C_NO
)
REFERENCES CONTENTS (
	C_NO
);

ALTER TABLE CONTENTSPEOPLE ADD CONSTRAINT FK_PEOPLE_TO_CONTENTSPEOPLE_1 FOREIGN KEY (
	PEOPLE_NO
)
REFERENCES PEOPLE (
	PEOPLE_NO
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_PRODUCT_TO_ORDERS_1 FOREIGN KEY (
	P_NO
)
REFERENCES PRODUCT (
	P_NO
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_MEMBER_TO_ORDERS_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

